FROM imabkanand/ytdownload-web:latest

# Example: Add custom Nginx config
# COPY custom-nginx.conf /etc/nginx/conf.d/default.conf

# # (Optional) Replace or add more frontend assets
# COPY extra-assets /usr/share/nginx/html/assets/

# Expose port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]